### ISSUE TITLE
決勝用ドキュメントの見直し、改善活動

### ISSUE THREAD

**Issue by yuasabe** [AutomotiveAIChallenge/aichallenge2023-integ#50]
- 分かりにくい箇所、もう少し詳細に書いた方が良い箇所、他懸念事項等をまとめる
- 実際に文章を書いて頂き、修正PRを出して頂く

**Comment by toki-1441** [comment]
## 現状報告 9/20
変更点は以下のとおりです(#51 も含めて)
#55
#56 
#58 

修正箇所が見つかり次第変更は行いますが、現状で修正しないといけない場所はないと思われます。
